title: Resources
description: >
  A curated list of links from the members of the
  Programming Discussions Discord server covering a
  wide variety of programming topics.

theme: jekyll-theme-cayman
